## **PCA + Logistic Regression (MNIST)**
The MNIST database of handwritten digits, available from this page, has a training set of 60,000 examples, and a test set of 10,000 examples. It is a subset of a larger set available from NIST. The digits have been size-normalized and centered in a fixed-size image.

Note: The MNIST database of handwritten digits is available on the following website: MNIST Dataset http://yann.lecun.com/exdb/mnist/

In [ ]:
from sklearn.datasets import fetch_openml
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import  metrics

In [ ]:
mnist = fetch_openml('mnist_784')
mnist

{'DESCR': "**Author**: Yann LeCun, Corinna Cortes, Christopher J.C. Burges  \n**Source**: [MNIST Website](http://yann.lecun.com/exdb/mnist/) - Date unknown  \n**Please cite**:  \n\nThe MNIST database of handwritten digits with 784 features, raw data available at: http://yann.lecun.com/exdb/mnist/. It can be split in a training set of the first 60,000 examples, and a test set of 10,000 examples  \n\nIt is a subset of a larger set available from NIST. The digits have been size-normalized and centered in a fixed-size image. It is a good database for people who want to try learning techniques and pattern recognition methods on real-world data while spending minimal efforts on preprocessing and formatting. The original black and white (bilevel) images from NIST were size normalized to fit in a 20x20 pixel box while preserving their aspect ratio. The resulting images contain grey levels as a result of the anti-aliasing technique used by the normalization algorithm. the images were centered i

In [ ]:
train_img,test_img,train_lbl,test_lbl =train_test_split(mnist.data,mnist.target,test_size = 0.3,random_state =123)


In [ ]:
train_img.shape

(49000, 784)

In [ ]:
train_img[0]

KeyError: ignored

In [ ]:
test_img.shape

(21000, 784)

In [ ]:
test_lbl.shape

(21000,)

In [ ]:
train_lbl.shape

(49000,)

In [ ]:
scaler = StandardScaler()
scaler.fit(train_img) #train images only

StandardScaler()

In [ ]:
len(scaler.mean_)

784

In [ ]:
# apply transformation to both train set and test set
train_img = scaler.transform(train_img)
test_img = scaler.transform(test_img)


In [ ]:
pca = PCA(n_components = 0.95)
pca.fit(train_img)

PCA(n_components=0.95)

In [ ]:
pca.n_components_

323

In [ ]:
pca.n_features_

784

In [ ]:
pca.explained_variance_

array([40.56433417, 29.02450546, 26.9313669 , 20.82318507, 18.09949744,
       15.76642964, 13.80416904, 12.50377938, 10.99211873, 10.01998328,
        9.63603355,  8.61609824,  8.03373451,  7.85245832,  7.38428803,
        7.12368823,  6.6711926 ,  6.60736488,  6.38803982,  6.18602659,
        5.88585565,  5.70980703,  5.42479437,  5.32512013,  5.14591301,
        4.95014549,  4.89075869,  4.68543709,  4.49574412,  4.38374361,
        4.25930905,  4.24722668,  4.05370693,  4.03020815,  3.93582713,
        3.87035527,  3.79911745,  3.71769374,  3.65712528,  3.44265486,
        3.43028049,  3.37734603,  3.26818015,  3.23695222,  3.22007253,
        3.18389961,  3.15121029,  3.09692565,  3.06735529,  3.01335066,
        2.91813999,  2.89598039,  2.84887891,  2.79389571,  2.74561286,
        2.72748097,  2.6979437 ,  2.62286342,  2.59195022,  2.57176634,
        2.51485824,  2.49088221,  2.45887784,  2.43188073,  2.42636139,
        2.39118472,  2.351282  ,  2.32707435,  2.29539544,  2.27

In [ ]:
pca.explained_variance_ratio_

array([0.05721228, 0.04093641, 0.03798423, 0.0293692 , 0.02552768,
       0.02223711, 0.01946952, 0.01763544, 0.01550338, 0.01413227,
       0.01359074, 0.01215222, 0.01133085, 0.01107517, 0.01041486,
       0.01004731, 0.00940911, 0.00931908, 0.00900975, 0.00872482,
       0.00830146, 0.00805316, 0.00765118, 0.00751059, 0.00725784,
       0.00698173, 0.00689797, 0.00660838, 0.00634084, 0.00618287,
       0.00600737, 0.00599032, 0.00571738, 0.00568424, 0.00555112,
       0.00545878, 0.00535831, 0.00524347, 0.00515804, 0.00485555,
       0.0048381 , 0.00476344, 0.00460947, 0.00456542, 0.00454162,
       0.0044906 , 0.00444449, 0.00436793, 0.00432622, 0.00425006,
       0.00411577, 0.00408452, 0.00401808, 0.00394053, 0.00387244,
       0.00384686, 0.0038052 , 0.00369931, 0.00365571, 0.00362724,
       0.00354698, 0.00351316, 0.00346802, 0.00342995, 0.00342216,
       0.00337255, 0.00331627, 0.00328213, 0.00323745, 0.00320459,
       0.00315687, 0.00315264, 0.00313085, 0.00309647, 0.00303

In [ ]:
pca.n_components

0.95

Apply Logistic regression

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
logisticRegr = LogisticRegression()
logisticRegr.fit(train_img,train_lbl)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression()

In [ ]:
test_img[0]

array([ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
       -4.51758561e-03, -4.51758561e-03, -6.24410946e-03, -8.43346592e-03,
       -1.16754848e-02, -1.87228033e-02, -2.51830921e-02, -3.06291938e-02,
       -3.15185398e-02, -3.21299739e-02, -3.35176259e-02, -3.06602340e-02,
       -3.02231644e-02, -2.68676314e-02, -2.20914325e-02, -1.89414044e-02,
       -1.70306363e-02, -1.08325340e-02, -7.69122172e-03, -4.51758561e-03,
        0.00000000e+00,  

In [ ]:
test_lbl[0]

KeyError: ignored

In [ ]:
logisticRegr.predict(test_img[0].reshape(1,-1))

array(['0'], dtype=object)

In [ ]:
test_lbl[0]

KeyError: ignored

In [ ]:
print(logisticRegr.predict(test_img[0:10]))

['0' '9' '4' '4' '5' '6' '1' '3' '1' '3']


In [ ]:
test_lbl[0:10]

21971    0
16953    9
48447    4
42344    9
4376     5
65743    6
64717    1
2820     3
57997    1
25377    3
Name: class, dtype: category
Categories (10, object): ['0', '1', '2', '3', ..., '6', '7', '8', '9']

In [ ]:
#test data accuracy
accuracy = logisticRegr.score(test_img,test_lbl)
accuracy

0.9138095238095238

In [ ]:
accuracy = logisticRegr.score(train_img,train_lbl)
accuracy

0.9456326530612245

In [ ]:
lR = LogisticRegression(solver='lbfgs')
lR.fit(train_img,train_lbl)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression()

In [ ]:
lR.predict(test_img[0].reshape(1,-1))

array(['0'], dtype=object)

In [ ]:
lR.predict(test_img[0:10])

array(['0', '9', '4', '4', '5', '6', '1', '3', '1', '3'], dtype=object)

In [ ]:
accuracy = lR.score(train_img,train_lbl)
accuracy

0.9456326530612245

In [ ]:
accuracy = lR.score(test_img,test_lbl)
accuracy

0.9138095238095238

In [ ]:
from sklearn.datasets import fetch_openml
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn import metrics
from sklearn.model_selection import train_test_split
import pandas as pd

Download and load data

In [ ]:
# You can add the parameter data_home to wherever to where you want to download your data
mnist = fetch_openml('mnist_784')
mnist

In [ ]:
# These are the images
mnist.data.shape

In [ ]:
# These are the labels
mnist.target.shape

**Splitting Data into Training and Test Sets**

In [ ]:
# test_size: what proportion of original data is used for test set
train_img, test_img, train_lbl, test_lbl = train_test_split(
    mnist.data, mnist.target, test_size=1/7.0, random_state=0)

In [ ]:
print(train_img.shape)

In [ ]:
print(train_img.shape)

In [ ]:
print(test_img.shape)

In [ ]:
print(test_lbl.shape)

**Standardizing the Data**
Since PCA yields a feature subspace that maximizes the variance along the axes, it makes sense to standardize the data, especially, if it was measured on different scales.



In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

# Fit on training set only.
scaler.fit(train_img)

# Apply transform to both the training set and the test set.
train_img = scaler.transform(train_img)
test_img = scaler.transform(test_img)

In [ ]:
from sklearn.decomposition import PCA

In [ ]:
pca = PCA(.95)
pca =PCA()

**Fit PCA on training set**

In [ ]:
X_norm_r = pca.fit(train_img)

In [ ]:
pca.n_components_

**Apply the mapping (transform) to both the training set and the test set.**

In [ ]:
train_img = pca.transform(train_img)
test_img = pca.transform(test_img)                  

# **PCA to Speed up Machine Learning Algorithms (Logistic Regression)**

Step 1: Import the model

In [ ]:
from sklearn.linear_model import LogisticRegression

Step 2: Make an instance of the Model

In [ ]:
# all parameters not specified are set to their defaults
# default solver is incredibly slow thats why we change it
# solver = 'lbfgs'
logisticRegr = LogisticRegression(solver = 'lbfgs')

Step 3: Training the model on the data, storing the information learned from the data

Model is learning the relationship between x (digits) and y (labels)

In [ ]:
logisticRegr.fit(train_img, train_lbl)

Step 4: Predict the labels of new data (new images)

Uses the information the model learned during the model training process

In [ ]:
# Returns a NumPy Array
# Predict for One Observation (image)
logisticRegr.predict(test_img[0].reshape(1,-1))

In [ ]:
# Predict for Multiple Observations (images) at Once
logisticRegr.predict(test_img[0:10])

Measuring Model Performance
accuracy (fraction of correct predictions): correct predictions / total number of data points

Basically, how the model performs on new data (test set)

In [ ]:
score = logisticRegr.score(test_img, test_lbl)
print(score)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')